class AppImages {
   var splash = "assets/images/splash.png";
   var link = "assets/images/link.png";
   var invite = "assets/images/invite.png";
   var copying = "assets/images/copying.png";
   var emptyBook = "assets/images/emptyBook.png";
   var emptyResult = "assets/images/emptyResult.png";
   var noChat = "assets/images/noChat.png";
   var noFav = "assets/images/noFav.png";
   var noNotification = "assets/images/noNotification.png";
   var noPayment = "assets/images/noPayment.png";
   var noResult = "assets/images/noResult.png";
   var phone = "assets/images/phone.png";
   var logo = "assets/images/logo.png";
   var email = "assets/images/email.png";
   var sure = "assets/images/sure.png";
   var google = "assets/images/google.png";
   var instagram = "assets/images/instagram.png";
   var facebook = "assets/images/facebook.png";
   var twitter = "assets/images/twitter.png";

   var lock = "assets/images/lock.png";
   var name = "assets/images/name.png";
   var logoutDoor = "assets/images/logoutDoor.png";
   var drop = "assets/images/drop.png";
   var otp = "assets/images/otp.png";
   var calendar = "assets/images/calendar.png";
   var marker = "assets/images/marker.png";
   var pin = "assets/images/pin.png";
   var p1 = "assets/images/p1.png";
   var p2 = "assets/images/p2.png";
   var p3 = "assets/images/p3.png";
   var people = "assets/images/people.png";
   var search = "assets/images/search.png";
   var searchFilled = "assets/images/searchBottom.png";
   var center = "assets/images/center.png";
   var indicator = "assets/images/indicator.png";
   var star = "assets/images/star.png";
   var inbox = "assets/images/inbox.png";
   var more = "assets/images/more.png";
   var v1 = "assets/images/v1.png";
   var v2 = "assets/images/v2.png";
   var v3 = "assets/images/v3.png";
   var cover = "assets/images/cover.png";
   var yacht1 = "assets/images/yacht1.png";
   var s1 = "assets/images/s1.png";
   var s2 = "assets/images/s2.png";
   var s3 = "assets/images/s3.png";
   var s4 = "assets/images/s4.png";
   var share = "assets/images/share.png";
   var apple = "assets/images/apple.png";
   var credit = "assets/images/credit.png";
   var appleLogo = "assets/images/appleLogo.png";
   var bin = "assets/images/bin.png";
   var crypto = "assets/images/crypto.png";
   var edit = "assets/images/edit.png";
   var checkmark = "assets/images/checkmark.png";
   var userDp = "assets/images/user_dp.png";
   var ask = "assets/images/ask.png";
   var check = "assets/images/check.png";
   var dropArrow = "assets/images/dropArrow.png";
   var feedback = "assets/images/feedback.png";
   var logout = "assets/images/logout.png";
   var personalInfo = "assets/images/personal_info.png";
   var shield = "assets/images/shield.png";
   var support = "assets/images/support.png";
   var switchToHost = "assets/images/switch_to_host.png";
   var translate = "assets/images/translate.png";
   var pp = "assets/images/pp.png";
   var bell = "assets/images/bell.png";
   var dropDown = "assets/images/drop_down.png";
   var peopleFill = "assets/images/people_fill.png";
   var markerFill = "assets/images/marker_fill.png";
   var location = "assets/images/location.png";
   var repeat = "assets/images/repeat.png";
   var searchBack = "assets/images/search_back.png";
   var fillCal = "assets/images/fill_cal.png";
   var radio = "assets/images/radio.png";
   var service1 = "assets/images/service1.png";
   var service2 = "assets/images/service2.png";
   var service3 = "assets/images/service3.png";
   var host2 = "assets/images/host2.png";
   var us = "assets/images/us.png";
   var uk = "assets/images/uk.png";
   var uae = "assets/images/uae.png";
   var vinny = "assets/images/vinny.png";
   var bodhi = "assets/images/bodhi.png";
   var leo = "assets/images/leo.png";
   var wheelGrey = "assets/images/wheelGrey.png";
   var cancel = "assets/images/cancel.png";
   var refund = "assets/images/refund.png";
   var listView = "assets/images/listView.png";
   var mapView = "assets/images/mapView.png";
   var owner = "assets/images/owner.png";
   var request = "assets/images/request.png";
   var pdf = "assets/images/pdf.png";
///
  var userImageUrl="https://firebasestorage.googleapis.com/v0/b/yacht-masters.appspot.com/o/user_dp.png?alt=media&token=b654eefe-534b-414d-bebd-1a3cdc7f3b8a";
  var dummyDp="https://firebasestorage.googleapis.com/v0/b/blogit-2cb31.appspot.com/o/dummyDp.jpeg?alt=media&token=ff065402-236c-4ee9-8e85-29f53617a4d3";
  var bodhiImageUrl="https://firebasestorage.googleapis.com/v0/b/yacht-masters.appspot.com/o/bodhi.png?alt=media&token=bcc92cdd-24bd-4192-8813-08aaa69a5bd4";
  var leoImageUrl="https://firebasestorage.googleapis.com/v0/b/yacht-masters.appspot.com/o/leo.png?alt=media&token=c29c1e19-ab3b-492e-badc-056ac7862872";
  var vinnyImageUrl="https://firebasestorage.googleapis.com/v0/b/yacht-masters.appspot.com/o/vinny.png?alt=media&token=dab0b845-8910-476d-811f-23410fa55973";
  var serviceUrl="https://firebasestorage.googleapis.com/v0/b/yacht-masters.appspot.com/o/s1.png?alt=media&token=75e3fbad-48ca-417b-aa3e-506c8d5dcf52";
}
