class LocalizationMap {
  static Map<String, String> codesEN = {
    "welcome_to_login": "Welcome to Login",
    "please_fill_email_password_to_login_your_app_account":
        "Please fill E-mail & password to login your app account.",
    "email": "E-mail",
    "email_hint": "admin@gmail.com",
    "please_enter_your_email_address": "Please enter your email address",
    "invalid_email_address": "Invalid email address",
    "password": "Password",
    "password_hint": "**************",
    "please_enter_your_password": "Please enter your password",
    "password_limit": "Password should be greater than 8 characters",
    "password_should_include_1_number": "Password should include 1 number",
    "password_should_1_special_character":
        "Password should include 1 special character",
    "forgot_password_question": "Forgot Password ?",
    "login_now": "Login Now",
    "password_reset_link_sent": "Password reset link sent",
    "forgot_password": "Forgot Password",
    "enter_your_registered_email_to_get_change_password_link":
        "Enter your registered Email to get change password link.",
    "save": "Save",
    "enter_email": "Enter email",
    "you_are_not_allowed_to_login": "You are not allowed to login",
    "admin": "Admin",
    "dashboard": "Dashboard",
    "users": "Users",
    "settings": "Settings",
    "change_password": "Change Password",
    "privacy_policy": "Privacy Policy",
    "terms_and_condition": "Terms & Condition",
    "logout": "Logout",
    "total_users": "Total Users",
    "all": "All",
    "search": "Search",
    "sr_no": "Sr #",
    "picture": "Picture",
    "name": "Name",
    "date": "Date",
    "email_caps": "Email",
    "status": "Status",
    "action": "Action",
    "no_data": "No Data",
    "please_provide_valid_password": "Please provide valid password",
    "password_changed_successfully": "Password changed successfully",
    "old_password": "Old Password",
    "please_enter_your_old_password": "Please enter your old password",
    "old_password_consists_minimum_8_character":
        "Old password consists minimum 8 character",
    "old_password_should_include_1_number":
        "Old password should include 1 number",
    "old_password_should_include_1_special_char":
        "Old password should include 1 special character",
    "please_enter_your_new_password": "Please enter your new password",
    "new_password_consists_minimum_8_character":
        "New password consists minimum 8 character",
    "new_password_should_include_1_number":
        "New password should include 1 number",
    "new_password_should_include_1_special_char":
        "New password should include 1 special character",
    "field_required": "Field is required",
    "active": "Active",
    "block": "Block",
    "required": "Field can't be empty",
    "new_password": "New Password",
    "new_password_and_old_password_cannot_be_same":
        "New password and old password cannot be same",
    "created_at": "Created At",
    "updated_at": "Updated At",
    "edit": "Edit",
    "content_management": "Content Management",
    "user_management": "User Management",
    "feedback_management": "Feedback Management",
    "feedback": "Feedback",
    "user_name": "User Name",
    "proceed": "Proceed",
    "reports": "Reports",
    "total_reports": "Total Feedback",
    "phone_number": "Phone Number",
    "total_friends": "Total Friends",
    "groups_joined": "Groups Joined",
    "yachtmaster": "YachtMaster",
    "pending": "Pending",
    "completed": "Completed",
    "created_date": "Created Date",
    "reported_by": "Reported by",
    "reported_to": "Reported to",
    "report_details": "Report Details",
    "report_titles": "Report Titles",
    "description": "Description",
    "reply": "Reply",
    "write_here": "Write here",
    "report_types": "Report Types",
    "title": "Title",
    "in_active": "In-Active",
    "deleted": "Deleted",
    "delete": "Delete",
    "add": "+ Add",
    "add_report_type": "Add Report Type",
    "cancellation_policy": "Cancellation Policy",
    "refund_policy": "Refund Policy",
    "feedback_details": "Feedback Details",
    "feedback_titles": "Feedback Titles",
    "customer": "Customers",
    "hosts": "Hosts",
    "user_details": "User Details",
    "charters": "Charters",
    "bookings": "Bookings",
    "booking_management": "Booking Management",
    "cancelled": "Cancelled",
    "ongoing": "OnGoing",
    "booked_by": "Booked by",
    "info": "Info",
    "charter_owner": "Charter Owner",
    "created_by": "Created by",
    "charter_detail": "Charter Detail",
    "booking_details": "Booking Detail",
    "time": "Time",
    "guests": "Guests",
    "schedule": "Schedule",
    "payment_management": "Payment Management",
    "request_management": "Request Management",
    "requests": "Requests",
    "payment": "Payment",
    "paid": "Paid",
    "received": "Received",
    "payment_details": "Payment Details",
    "service_fee": "Service Fee",
    "sub_total": "Sub Total",
    "taxes": "Taxes",
    "tip": "Tip",
    "total": "Total",
    "active_chats": "Active Chats",
    "enter_message": "Enter Message",
    "chats": "Chats",
    "chat": "Chat",
    "not_host": "Not Host",
    "host": "Host",
    "reject": "Reject",
    "accept": "Accept",
    "accepted": "Accepted",
    "user": "User",
    "total_requests": "Total Requests",
    "total_bookings": "Total Bookings",
    "total_charters": "Total Charters",
    "total_yachts": "Total Yachts",
    "total_services": "Total Services",
    "documents": "Documents",
    "service_and_taxes": "Service & Taxes",
    "service_tax": "Service Tax",
    "enter_service_fee": "Enter Service Fee",
    "enter_tax": "Enter Tax",
    "tax": "Tax",
    "tips": "Tips",
    "enter_tip": "Enter Tip",
    "enter_referral_amount": "Enter Referral Amount",
    "referral_amount": "Referral Amount",
    "start_date_time": "Start Date & Time",
    "end_date_time": "End Date & Time",
    "payment_verification_requests": "Payment Verification Requests",
    "accepted": "Accepted",
    "ch_pic": "Change Media on Home Page",
    "up_save": "Choose and Upload Image",
  };

  static String getTranslatedValues(String key) {
    return codesEN[key] ?? "";
  }
}
